name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0 # Replace with your project's .NET version

      # Step 3: Restore dependencies
      - name: Restore dependencies
        run: dotnet restore PA.Common.sln
        working-directory: src/PA.Common

      # Step 4: Build the solution
      - name: Build solution
        run: dotnet build PA.Common.sln --no-restore
        working-directory: src/PA.Common

      # Step 5: Run tests
      - name: Run tests
        run: dotnet test PA.Common.sln --no-build --verbosity normal
        working-directory: src/PA.Common
